services:

  app:
    build:
      context: dockerfiles/php
      dockerfile: Dockerfile
    container_name: skiltask_app
    volumes:
      - .:/var/www/skiltask
    networks:
      - skiltask_network
    restart: unless-stopped


  nginx:
    image: nginx:alpine
    container_name: skiltask_nginx
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/skiltask
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - skiltask_network
    depends_on:
      - app


  db:
    image: mysql:8.0
    container_name: skiltask_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: skiltask
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    networks:
      - skiltask_network
    volumes:
      - dbdata:/var/lib/mysql


networks:
  skiltask_network:

volumes:
  dbdata:
